spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.31.219:3306/sa_xzs?autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: zhny
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
